node_js:
  - 'node'
services:
  - postgresql
before_script:
  - npm install -g mocha
  - npm install -g nyc
  - npm install -g sequelize-cli
  - psql -c 'create database test;' -U postgres
script:
  - npm test
after_script: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

after_success: 
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < ./coverage/lcov.info
  - ./node_modules/.bin/coveralls --verbose < coverage/lcov.info
